theme: jekyll-theme-minimal
title: Santhoshkumar S
email: santhoshramuk@gmail.com
twitter_username: santhosh790
description: A Personal Website of Santhoshkumar to showcase his current profile and track all his works and researches
